version: 2.1

orbs:
  orb-tools: circleci/orb-tools@2.0.2

executors:
  cli:
    docker:
      - image: circleci/circleci-cli:0.1.2709

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - lint

      - validate:
          requires:
            - lint

      - publish-dev:
          requires:
            - validate

      - promote-prod:
          name: publish-patch-release
          requires:
            - publish-dev
          filters:
            branches:
              only: master

jobs:
  lint:
    docker:
      - image: singapore/lint-condo
    steps:
      - checkout
      - run: yamllint .

  validate:
    executor: cli
    steps:
      - checkout

      - orb-tools/pack:
          source: src
          destination: orb.yml

      - run: circleci orb validate orb.yml

      - store_artifacts:
          path: orb.yml

  publish-dev:
    executor: cli
    steps:
      - checkout
      - run: circleci orb publish orb.yml iynere/compare-url@dev:$CIRCLE_BRANCH-$CIRCLE_SHA1 --token $CIRCLE_TOKEN

  promote-prod:
    executor: cli
    parameters:
      release:
        type: enum
        default: "patch"
        enum: ["patch", "minor", "major"]

    steps:
      - checkout
      - run: circleci orb publish promote iynere/compare-url@dev:$CIRCLE_BRANCH-$CIRCLE_SHA1 <<parameters.release>> --token $CIRCLE_TOKEN
