version: 2.1

executors:
  cli:
    docker:
      - image: circleci/circleci-cli:0.1.2709

jobs:
  lint:
    docker:
      - image: singapore/lint-condo
    steps:
      - checkout
      - run: yamllint .

  validate:
    executor: cli
    steps:
      - checkout
      - run: circleci orb validate src/@orb.yml

  publish-dev:
    executor: cli
    steps:
      - checkout
      - run: circleci orb publish src/@orb.yml iynere/compare-url@dev:$CIRCLE_BRANCH-$CIRCLE_SHA1 --token $CIRCLE_TOKEN

  promote-prod:
    executor: cli
    parameters:
      release:
        type: enum
        default: "patch"
        enum: ["patch", "minor", "major"]

    steps:
      - checkout
      - run: circleci orb publish promote iynere/compare-url@dev:$CIRCLE_BRANCH-$CIRCLE_SHA1 <<parameters.release>> --token $CIRCLE_TOKEN

workflows:
  version: 2
  test-deploy:
    jobs:
      - lint

      - validate:
          requires:
            - lint

      - publish-dev:
          requires:
            - validate

      - promote-prod:
          name: promote-patch-release
          requires:
            - publish-dev
          filters:
            branches:
              only: master

  test-deploy-tagged:
    jobs:
      - lint:
          filters:
            tags:
              only: /release-*/
            branches:
              ignore: /.*/

      - validate:
          requires:
            - lint
          filters:
            tags:
              only: /release-*/
            branches:
              ignore: /.*/

      - publish-dev:
          requires:
            - validate
          filters:
            tags:
              only: /release-*/
            branches:
              ignore: /.*/

      - promote-prod:
          name: promote-minor-release
          requires:
            - publish-dev
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /release-minor*/

      - promote-prod:
          name: promote-major-release
          requires:
            - publish-dev
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /release-major*/
