version: 2.1

orbs:
  orb-tools: circleci/orb-tools@2.0.2
  circle-compare-url-test: iynere/compare-url@dev:alpha
  circle-compare-url: iynere/compare-url@0.1.10

executors:
  ci-base:
    resource_class: small
    docker:
      - image: cibuilds/base

  cli:
    resource_class: small
    docker:
      - image: circleci/circleci-cli:0.1.2709

  lint-condo:
    resource_class: small
    docker:
      - image: singapore/lint-condo

workflows:
  version: 2
  build-and-test:
    jobs:
      - lint

      - validate:
          requires:
            - lint

      - publish-dev:
          requires:
            - validate

      - trigger-integration:
          name: trigger-integration-dev
          requires:
            - publish-dev

      - trigger-integration:
          name: trigger-integration-master
          tag: master
          requires:
            - publish-dev
          filters:
            branches:
              only: master

  integrate-and-deploy:
    jobs:
      - circle-compare-url-test/reconstruct:
          name: integration-test-dev
          resource-class: small
          debug: true
          debug-steps:
            - circle-compare-url-test/reconstruct:
                debug: true
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /integration-.*/

      - circle-compare-url-test/reconstruct:
          name: integration-test-master
          resource-class: small
          debug: true
          debug-steps:
            - circle-compare-url-test/reconstruct:
                debug: true
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-.*/

      - dev-promote-prod:
          requires:
            - integration-test-master
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-.*/

jobs:
  lint:
    executor: lint-condo
    steps:
      - checkout
      - run: yamllint .

  validate:
    executor: cli
    steps:
      - checkout

      - orb-tools/pack:
          source: src
          destination: orb.yml

      - run: circleci orb validate orb.yml

      - store_artifacts:
          path: orb.yml

      - persist_to_workspace:
          root: .
          paths:
            - orb.yml

  publish-dev:
    executor: cli
    steps:
      - checkout

      - attach_workspace:
          at: workspace

      - run:
          name: publish w/branch & sha (for transparency)
          command: circleci orb publish workspace/orb.yml iynere/compare-url@dev:$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7} --token $CIRCLE_TOKEN

      - run:
          name: publish alpha (for immediate integration testing)
          command: circleci orb publish workspace/orb.yml iynere/compare-url@dev:alpha --token $CIRCLE_TOKEN

  trigger-integration:
    executor: ci-base
    parameters:
      tag:
        type: enum
        default: "integration"
        enum: ["integration", master]
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "b2:c0:00:a5:2e:87:cf:ac:5b:90:67:85:09:8c:c8:54"

      - run:
          name: git config
          command: |
            git config --global user.email "$CIRCLE_USERNAME@users.noreply.github.com"
            git config --global user.name "$CIRCLE_USERNAME"

      - run: |
          INTEGRATION_TAG=<<parameters.tag>>-$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7}
          git tag $INTEGRATION_TAG
          git push origin $INTEGRATION_TAG

  dev-promote-prod:
    executor: cli
    steps:
      - checkout

      - circle-compare-url/reconstruct:
          debug: true

      - run:
          name: publish minor release if src/ modified, otherwise  patch
          command: |
            CIRCLE_COMPARE_URL=$(cat CIRCLE_COMPARE_URL.txt)

            COMMIT_RANGE=$(echo $CIRCLE_COMPARE_URL | sed 's:^.*/compare/::g')

            echo "Commit range: $COMMIT_RANGE"

            if [[ $(git diff $COMMIT_RANGE --name-status | grep "src/") ]]; then
              circleci orb publish promote iynere/compare-url@dev:$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7} minor --token $CIRCLE_TOKEN
            else
              circleci orb publish promote iynere/compare-url@dev:$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7} patch --token $CIRCLE_TOKEN
            fi
